### ISSUE TITLE
Django Lessons to be Completed

### ISSUE THREAD

**Issue by mkelvs** [mkelvs/Djangoprojects#2]
## TODO

*Django lessons left to be completed

- [x] Django Basics (Views, Models, Templates)
- [x] Customizing Django Templates
- [x] Django Forms
- [x] Django ORM
- [x] Customizing the Django Admin
- [x] Django Class-based Views
- [x] Rest API Basics
- [x] Django REST Framework
- [x] Django Authentication
- [x] Django Social Authentication

🎉 💯 🎊
